### ISSUE TITLE
Getting [1]  40872 illegal hardware instruction 

### ISSUE THREAD

**Issue by dikshant** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#60] opened 2018-03-31 01:23 UTC
I built the kinesis_videogrstreamer_sample_app on macOS High Sierra but when I tried doing ./kinesis_video_gstreamer_sample_app mystreamname I get the error above. My credentials are correct. 

What is this error message referring to?

**Comment by briancarbs** [comment] 2018-04-10 20:49
Hey figured I'd include my log as well. Ran into something similar while attempting to run the rtsp example. Everything seemed to compiled fine on osx 10.13.3 ...
`[100%] Linking CXX executable kinesis_video_gstreamer_sample_rtsp_app
[100%] Built target kinesis_video_gstreamer_sample_rtsp_app
**********************************************************
Success!!!
**********************************************************`
but right as the app attempts to refresh the credentials and create the video stream it fails with...
Illegal instruction: 4

Let me know if there's anything I can do to help debug, thanks!

/var/log/system.log
`Apr 10 16:38:44 carbs com.apple.xpc.launchd[1] (com.apple.quicklook[26601]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
Apr 10 16:40:45 carbs com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Apr 10 16:42:39 carbs systemstats[61]: assertion failed: 17D102: systemstats + 691122 [709BF19E-7F73-373B-A9AC-18949BF612F2]: 0x5
Apr 10 16:42:39 carbs syslogd[51]: ASL Sender Statistics`

**Comment by unicornss** [comment] 2018-04-11 20:17
Thanks @briancarbs. This seems to be specific to the High Sierra with the latest patch; we will update you once we identify what is causing this issue in that run time environment.

**Comment by nikparmar** [comment] 2018-04-25 03:33
Hey @unicornss any update here ?

**Comment by unicornss** [comment] 2018-04-25 17:32
Hi @nikparmar 
The issue is caused from the latest tool chain update (Commandline tools for Xcode).
It has been fixed and currently been deployed in the staging environment (Mac High Sierra 10.13).  Will be releasing it shortly. Sorry for the inconvenience.  
Thanks

**Comment by zhiyua-git** [comment] 2018-04-25 21:08
@dikshantad @briancarbs @nikparmar We just released the version 1.4.0 fixing this issue, can you check it out and have a try? Thanks.

**Comment by nikparmar** [comment] 2018-04-26 14:11
Hey @zhiyua-git need to build everything again -.-?

**Comment by unicornss** [comment] 2018-04-26 15:58
Glad you are able to get this built in Mac High Sierra now.  

Closing this post for now. Pl. reopen if needed.
Thanks

**Closed as completed by unicornss** 2018-04-26 15:58 UTC
Labels: high sierra
