### ISSUE TITLE
How to change stream producer Timezone?

### ISSUE THREAD

**Issue by kamlesh545** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#352] opened 2020-02-23 18:12 UTC
Hi,

How to change stream producer Timezone in kinesis video stream sdk? 
currently my default timezone is GMT I want to change this into IST how can i change this timezone ?
This following is my debug log of kinesis sdk 
[INFO ] [23-02-2020 16:13:02:981.826 GMT] Using region: ap-northeast-1

**Comment by MushMal** [comment] 2020-02-24 19:10
@kamlesh545 there are a couple of issues here depending on the configuration of your application. 1) If you are using frame timestamp mode configuration (default) then your media pipeline would timestamp the frames. 2) If you are using SDK timestamp mode then the SDK would call default get current time API to timestamp of the frames. By default, it's the GETTIME() macro in PIC which will depend on the architecture and platform you are using. Check utils/Time.cpp

Next, if you are using the Relative mode then the PutMedia StreamStart parameter of the backend API will be set using the same get current time API.

In this case though, it seems that you simply want the logs to display the local TZ timestamp. If so, change GMTIME()

https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/kinesis-video-pic/src/utils/src/Time.c#L19

to a local time using localtime CRT api.

**Comment by kamlesh545** [comment] 2020-02-25 04:11
Hi Mushmal,

Thanks for your reply can you tell me in utils/Time.cpp file after remove GMTIME() function what fucntion should i add to get local Timestamp ?

Thanks.

**Comment by disa6302** [comment] 2020-02-25 12:05
Hello @kamlesh545 ,

You can replace the line mentioned by @MushMal  by:

formattedStrLen = (UINT32) STRFTIME(pDestBuffer, destBufferLen, formatStr, LOCALTIME(&timestampSeconds))

**Comment by kamlesh545** [comment] 2020-02-25 17:27
Hello @disa6302 ,

Thanks for your reply when i changed GMT to LOCALTIME as you mentioned and after again compile all files with ./min-install-script command i m getting compile error at this following stage
[ 85%] Linking CXX shared library libproducer.so

**Comment by disa6302** [comment] 2020-02-25 18:19
Can you try localtime in lower case? The failure is probably because LOCALTIME is not defined in our pic CommonDefs.h file.

**Comment by kamlesh545** [comment] 2020-02-25 18:37
after changed with lowercase localtime compiled successfully but after starting stream still i am getting GMT timestamp why?

**Comment by zhiyua-git** [comment] 2020-02-25 20:22
Hi @kamlesh545 ,

Seems you are using gstreamer sample which uses log4cplus, you can change this https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/2.1.0/kinesis-video-native-build/kvs_log_configuration#L8 to [%D{%d-%m-%Y %H:%M:%S:%Q %Z}] to get local time. Thanks.

**Comment by disa6302** [comment] 2020-03-04 22:16
Hello @kamlesh545 , 

Can you close this ticket if the issue is resolved? 

Thanks!

**Comment by disa6302** [comment] 2020-03-09 21:09
Closing this for now. @kamlesh545 , feel free to create a new issue if you face any problems in the future.

**Closed by disa6302** 2020-03-09 21:09 UTC
Labels: assumed answered, question
