### ISSUE TITLE
resolution 1920x1080 vs 640*480

### ISSUE THREAD

**Issue by robo-dynamix** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#1100] opened 2023-11-08 08:55 UTC
hello ,aws

   i encounter some confusion. when set frame is 1920x1080 ,i fail to push rtsp into aws server. when i set 640x480, i can success to accept the video streaming in aws. can you explain this confusion?https://sxj731533730.blog.csdn.net/article/details/134287577?spm=1001.2014.3001.5502&ydreferer=aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3N4ajczMTUzMzczMD90eXBlPWJsb2c%3D

你好 官方开发人员
   我遇到一个问题，当我设置摄像头的分辨率是1920 x1080 是无法推送流到亚马逊服务上，但是我设置640x480是可以推送到流媒体服务上的，这是什么原因的呢？能帮我解释一下吗

**Comment by hassanctech** [comment] 2023-11-20 17:36
There is no limitation on frame size.  We cannot provide any guidance here without DEBUG logging to indicate what the issue is. Also please indicate which version of the SDK you are using. I'm closing this issue as no details have been provided.  If you provided side by side your configuration for the working and non working case as well as DEBUG level logs from the SDK, then please re-open or create a new issue with those details.

**Closed by hassanctech** 2023-11-20 17:36 UTC
Labels: question
